version: '3.8'

services:
  app-service:
    build: ./app-service
    container_name: app-service
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - app-network

  simulator-service:
    build: ./simulator-service
    container_name: simulator-service
    ports:
      - "3001:3001"
    environment:
      - DEVICE_NAME="iPhone 12"
      - PLATFORM_VERSION="14.4"
    depends_on:
      - app-service
    networks:
      - app-network

  proxy-service:
    build: ./proxy-service
    container_name: proxy-service
    ports:
      - "3002:3002"
    environment:
      - SIMULATOR_SERVICE_URL=http://simulator-service:3001
    depends_on:
      - simulator-service
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
